#!/bin/bash

##################################### DEFs #####################################

################################### MESSAGES ###################################
MESSAGES=1
MESSAGES_RATE=1
MESSAGES_RATE_PERIOD=1000
MESSAGES_PAUSE=10000


################################### FILEs ######################################
DIR_PWD=`pwd`
DIR_CSV=$DIR_PWD/csv
DIR_XML=$DIR_PWD/xml

UAC_CSV=uac.csv
UAS_CSV=uas.csv

UAC_XML=uac.xml
UAS_XML=uas.xml


################################## SIP/RTP ###################################
SRV_SIP_IP=X.X.X.X
SRV_SIP_PORT=5060

UAC_SIP_IP=Y.Y.Y.Y
UAC_SIP_PORT=1110

UAS_SIP_IP=Y.Y.Y.Y
UAS_SIP_PORT=2220

UAC_RTP_IP=Y.Y.Y.Y
UAC_RTP_PORT_MIN=10000
UAC_RTP_PORT_MAX=11999

UAS_RTP_IP=Y.Y.Y.Y
UAS_RTP_PORT_MIN=30000
UAS_RTP_PORT_MAX=31999
