#!/bin/bash

##################################### DEFs #####################################

################################### MESSAGES ###################################
MESSAGES=1
MESSAGES_RATE=1
MESSAGES_RATE_PERIOD=1000
MESSAGES_PAUSE=10000


################################### FILEs ######################################
DIR_PWD=`pwd`
DIR_CSV=$DIR_PWD/csv
DIR_XML=$DIR_PWD/xml

UAC_CSV=uac.csv
UAS_CSV=uas.csv

UAC_XML=uac.xml
UAS_XML=uas.xml


################################## SIP/RTP ###################################
SRV_SIP_IP=192.168.100.57
SRV_SIP_PORT=50060

UAC_SIP_IP=192.168.100.3
UAC_SIP_PORT=1112

UAS_SIP_IP=192.168.100.3
UAS_SIP_PORT=2222

UAC_RTP_IP=192.168.100.3
UAC_RTP_PORT_MIN=14000
UAC_RTP_PORT_MAX=15999

UAS_RTP_IP=192.168.100.3
UAS_RTP_PORT_MIN=34000
UAS_RTP_PORT_MAX=35999
